/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface DecimalMathInterface extends ethers.utils.Interface {
  functions: {
    "PRECISE_UNIT()": FunctionFragment;
    "UNIT()": FunctionFragment;
    "decimals()": FunctionFragment;
    "highPrecisionDecimals()": FunctionFragment;
    "preciseUnit()": FunctionFragment;
    "unit()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "PRECISE_UNIT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "UNIT", values?: undefined): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "highPrecisionDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "preciseUnit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unit", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "PRECISE_UNIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "UNIT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "highPrecisionDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "preciseUnit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unit", data: BytesLike): Result;

  events: {};
}

export class DecimalMath extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DecimalMathInterface;

  functions: {
    PRECISE_UNIT(overrides?: CallOverrides): Promise<[BigNumber]>;

    "PRECISE_UNIT()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    UNIT(overrides?: CallOverrides): Promise<[BigNumber]>;

    "UNIT()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    decimals(overrides?: CallOverrides): Promise<[number]>;

    "decimals()"(overrides?: CallOverrides): Promise<[number]>;

    highPrecisionDecimals(overrides?: CallOverrides): Promise<[number]>;

    "highPrecisionDecimals()"(overrides?: CallOverrides): Promise<[number]>;

    preciseUnit(overrides?: CallOverrides): Promise<[BigNumber]>;

    "preciseUnit()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    unit(overrides?: CallOverrides): Promise<[BigNumber]>;

    "unit()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  PRECISE_UNIT(overrides?: CallOverrides): Promise<BigNumber>;

  "PRECISE_UNIT()"(overrides?: CallOverrides): Promise<BigNumber>;

  UNIT(overrides?: CallOverrides): Promise<BigNumber>;

  "UNIT()"(overrides?: CallOverrides): Promise<BigNumber>;

  decimals(overrides?: CallOverrides): Promise<number>;

  "decimals()"(overrides?: CallOverrides): Promise<number>;

  highPrecisionDecimals(overrides?: CallOverrides): Promise<number>;

  "highPrecisionDecimals()"(overrides?: CallOverrides): Promise<number>;

  preciseUnit(overrides?: CallOverrides): Promise<BigNumber>;

  "preciseUnit()"(overrides?: CallOverrides): Promise<BigNumber>;

  unit(overrides?: CallOverrides): Promise<BigNumber>;

  "unit()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    PRECISE_UNIT(overrides?: CallOverrides): Promise<BigNumber>;

    "PRECISE_UNIT()"(overrides?: CallOverrides): Promise<BigNumber>;

    UNIT(overrides?: CallOverrides): Promise<BigNumber>;

    "UNIT()"(overrides?: CallOverrides): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<number>;

    "decimals()"(overrides?: CallOverrides): Promise<number>;

    highPrecisionDecimals(overrides?: CallOverrides): Promise<number>;

    "highPrecisionDecimals()"(overrides?: CallOverrides): Promise<number>;

    preciseUnit(overrides?: CallOverrides): Promise<BigNumber>;

    "preciseUnit()"(overrides?: CallOverrides): Promise<BigNumber>;

    unit(overrides?: CallOverrides): Promise<BigNumber>;

    "unit()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    PRECISE_UNIT(overrides?: CallOverrides): Promise<BigNumber>;

    "PRECISE_UNIT()"(overrides?: CallOverrides): Promise<BigNumber>;

    UNIT(overrides?: CallOverrides): Promise<BigNumber>;

    "UNIT()"(overrides?: CallOverrides): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    "decimals()"(overrides?: CallOverrides): Promise<BigNumber>;

    highPrecisionDecimals(overrides?: CallOverrides): Promise<BigNumber>;

    "highPrecisionDecimals()"(overrides?: CallOverrides): Promise<BigNumber>;

    preciseUnit(overrides?: CallOverrides): Promise<BigNumber>;

    "preciseUnit()"(overrides?: CallOverrides): Promise<BigNumber>;

    unit(overrides?: CallOverrides): Promise<BigNumber>;

    "unit()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    PRECISE_UNIT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "PRECISE_UNIT()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    UNIT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "UNIT()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "decimals()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    highPrecisionDecimals(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "highPrecisionDecimals()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    preciseUnit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "preciseUnit()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "unit()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
