/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ICeloRegistryInterface extends ethers.utils.Interface {
  functions: {
    "getAddressFor(bytes32)": FunctionFragment;
    "getAddressForOrDie(bytes32)": FunctionFragment;
    "isOneOf(bytes32[],address)": FunctionFragment;
    "setAddressFor(string,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAddressFor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressForOrDie",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOneOf",
    values: [BytesLike[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddressFor",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAddressFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddressForOrDie",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOneOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAddressFor",
    data: BytesLike
  ): Result;

  events: {};
}

export class ICeloRegistry extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ICeloRegistryInterface;

  functions: {
    getAddressFor(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getAddressFor(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getAddressForOrDie(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getAddressForOrDie(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isOneOf(
      arg0: BytesLike[],
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isOneOf(bytes32[],address)"(
      arg0: BytesLike[],
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setAddressFor(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setAddressFor(string,address)"(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getAddressFor(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  "getAddressFor(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getAddressForOrDie(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "getAddressForOrDie(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  isOneOf(
    arg0: BytesLike[],
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isOneOf(bytes32[],address)"(
    arg0: BytesLike[],
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setAddressFor(
    arg0: string,
    arg1: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setAddressFor(string,address)"(
    arg0: string,
    arg1: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getAddressFor(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    "getAddressFor(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getAddressForOrDie(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "getAddressForOrDie(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    isOneOf(
      arg0: BytesLike[],
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isOneOf(bytes32[],address)"(
      arg0: BytesLike[],
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setAddressFor(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAddressFor(string,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getAddressFor(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAddressFor(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAddressForOrDie(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAddressForOrDie(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOneOf(
      arg0: BytesLike[],
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isOneOf(bytes32[],address)"(
      arg0: BytesLike[],
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setAddressFor(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setAddressFor(string,address)"(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAddressFor(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAddressFor(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAddressForOrDie(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAddressForOrDie(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isOneOf(
      arg0: BytesLike[],
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isOneOf(bytes32[],address)"(
      arg0: BytesLike[],
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAddressFor(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setAddressFor(string,address)"(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
