/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ReserveInterface extends ethers.utils.Interface {
  functions: {
    "amm()": FunctionFragment;
    "kresko()": FunctionFragment;
    "transferStableTokenToAMM(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "amm", values?: undefined): string;
  encodeFunctionData(functionFragment: "kresko", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferStableTokenToAMM",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "amm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kresko", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferStableTokenToAMM",
    data: BytesLike
  ): Result;

  events: {};
}

export class Reserve extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ReserveInterface;

  functions: {
    amm(overrides?: CallOverrides): Promise<[string]>;

    "amm()"(overrides?: CallOverrides): Promise<[string]>;

    kresko(overrides?: CallOverrides): Promise<[string]>;

    "kresko()"(overrides?: CallOverrides): Promise<[string]>;

    transferStableTokenToAMM(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferStableTokenToAMM(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  amm(overrides?: CallOverrides): Promise<string>;

  "amm()"(overrides?: CallOverrides): Promise<string>;

  kresko(overrides?: CallOverrides): Promise<string>;

  "kresko()"(overrides?: CallOverrides): Promise<string>;

  transferStableTokenToAMM(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferStableTokenToAMM(uint256)"(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    amm(overrides?: CallOverrides): Promise<string>;

    "amm()"(overrides?: CallOverrides): Promise<string>;

    kresko(overrides?: CallOverrides): Promise<string>;

    "kresko()"(overrides?: CallOverrides): Promise<string>;

    transferStableTokenToAMM(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferStableTokenToAMM(uint256)"(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    amm(overrides?: CallOverrides): Promise<BigNumber>;

    "amm()"(overrides?: CallOverrides): Promise<BigNumber>;

    kresko(overrides?: CallOverrides): Promise<BigNumber>;

    "kresko()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferStableTokenToAMM(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferStableTokenToAMM(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    amm(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "amm()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    kresko(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "kresko()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferStableTokenToAMM(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferStableTokenToAMM(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
